/*
 * Pro-Watch API REST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 771c6a63-9da8-4300-b275-33061d174776
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model201 {
    #[serde(rename = "ResourceID", skip_serializing_if = "Option::is_none")]
    pub resource_id: Option<String>,
}

impl Model201 {
    pub fn new() -> Model201 {
        Model201 {
            resource_id: None,
        }
    }
}
